name: phi-2
model_HF_cls:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: microsoft/phi-2

tokenizer_HF_cls:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: microsoft/phi-2